project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "STAT 306: Finding Relationships in Data"
        contents:
          - index.qmd
          - CODE_OF_CONDUCT.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


