---
title: "Syllabus"
subtitle: "STAT 306: Finding Relationships in Data"
---

## Time and place

-   See UBC Calendar

## Course description
Modelling a response (output) variable 
as a function of several explanatory (input) variables: 
multiple regression for a continuous response, 
logistic regression for a binary response, 
and log-linear models for count data. 
Finding low-dimensional structure: principal components analysis. 
Cluster analysis.

## Prerequisite
One of MATH 152, MATH 221, 
MATH 223 and one of STAT 200, STAT 241, STAT 251, STAT 300, BIOL 300, BUSI 291, 
COMM 191, COMM 291, ECON 325, ECON 327, FRST 231, PSYC 218, PSYC 278 
and one of MATH 302, STAT 302.

## Textbook

The course notes, which can be ordered from the UBC bookstore, are:
-Joe, H. (2020): Course Notes for STAT 306: Finding Relationships in Data.

Other useful texts, both available via the library website, are:
- Chatterjee, S. and Hadi, A.S. (2006): Regression Analysis by Example, (4th
edit.). Wiley (In particular chapters 1ñ6, 11, 9.1-9.7, 12.1-12.7, 13.3 are cov-
ered.)
- Pardoe, I. (2020): Applied Regression Modeling, (3rd edit.). Wiley. (2nd
edition (2012) also helpful.

## Hardware & software

Students are required to bring a laptop to both lectures and tutorials.
We will be using the the programming language R,
the Quarto scientific and technical publishing system,
and the RStudio Desktop integrated development environment (IDE).
Visit the links below to download the version of software needed 
for your operating system, and install it on your laptop.
- [R programming language](https://cran.r-project.org/)
- [RStudio Desktop](https://posit.co/download/rstudio-desktop/)
- [Quarto](https://quarto.org/docs/get-started/)

## Objectives
On completing the course, 
students should be able to demonstrate an understanding of the techniques 
and applications of well known ideas in linear modelling, 
including model fitting, model selection, model diagnostics, 
as well as basic ideas for generalised linear models and principal
components analysis.

## Learning outcomes

1. Understand the principles of model fitting and inference for linear models 
involving a response variable with a single explanatory variable.
2. Understand the role of residuals in linear regression, including model
diagnostics.
3. Appreciate and apply key concepts of linear modelling when there is
more than one explanatory variable.
4. Understand and apply linear model theory to cases where at least one
explanatory variable is categorical.
5. Critique studies that involve regression methods, 
including identification of any flaws and limitations to inferences.
6. Apply commonly used methods for model selection 
in a multiple regression context.
7. Use and interpret common approaches to identifying influential data
points and outliers in a regression context.
8. Apply and interpret linear models that involve the transformation of
one or more variable.
9. Apply and interpret a principal components analysis (PCA).
10. Understand and apply concepts from generalised linear modelling,
including logistic and Poisson regression.
11. Apply linear modelling methods in the software R, using appropriate
R functions and interpreting the output.

## Teaching Team

|         Position     |        Name     | Email                            | Office Hours     | Office Location |
|:--------------------:|:---------------:|:--------------------------------:|:----------------:|:---------------:|
|    Instructor        | Lucy Gao        |                                  | TBD              | See Canvas      |
|    Instructor        | Tiffany Timbers | tiffany.timbers[-at-]stat.ubc.ca | TBD              | See Canvas      |
|    TA                |                 |                                  | TBD              | See Canvas      |

## Assessment

### Grading breakdown

<!-- read in a csv -->

## Schedule at a glance

<!-- read in a csv -->

### Assessment schedule

In general, assignments will be due 11:59 PM on Saturdays. However, in
the final week of classes, all assignments need to be submitted by the
final day of classes, thus we have two alternative due dates that week.

<!-- read in a csv -->

## Policies

### Code of Conduct

All participants in our course and communications are expected to show
respect and courtesy to others. To creating a friendly and respectful
place for learning, teaching and contributing, you are expected to read
and follow the [DSCI 310 Code of
Conduct](https://ubc-dsci.github.io/dsci-310-student/coc.html).

### Late registration

Students who register for the class late have 1 week from their
registration date on Canvas to complete all prior assignments.

### Late assignments / mid-term exam absence

Students **must be present** at the invigilation venue (in class, on
Zoom, examination centre, etc) to take the mid-term exam; otherwise they
will be considered to have missed the mid-term exam and will be assigned
a grade of zero.

Students who will miss the mid-term exam **must provide a
self-declaration prior to the mid-term exam** and make arrangements
(e.g., schedule an oral make-up mid-term exam) with the Instructor.
Failing to present a declaration within a reasonable timeframe before
the mid-term exam will result in a grade of zero.

A late submission is defined as any work submitted after the deadline.
For a late submission, the student will receive a 75% scaling of their
grade for the first occurrence, 50% scaling of their grade for the
second occurrence, and will receive a grade of 0 for subsequent
occurrences.

Students who miss an assignment or quiz can request an academic
concession. From the [UBC Senate policy on academic
concession](https://senate.ubc.ca/sites/senate.ubc.ca/files/downloads/20190515_V_135_Academic_Concession-Approved.pdf),
grounds for academic concession can be illness, conflicting
responsibilities, or compassionate grounds. Examples of compassionate
grounds, from the above policy, include “a traumatic event experienced
by the student, a family member, or a close friend; an act of sexual
assault or other sexual misconduct experienced by the student, a family
member, or a close friend; a death in the family or of a close friend.”

To request an academic concession, students should immediately email a
completed and signed [academic concession form to the course
Instructor](https://github.com/UBC-MDS/UBC-MDS.github.io/blob/master/img/Template%20-%20In-Term%20Academic%20Concessions%20Self%20Declaration.pdf?raw=1).
Upon receiving the form, the Instructor will make a decision about how
to proceed. Failure to present valid documentation may result in a
failing grade.

### Re-grading

If you have concerns about the way your work was graded, please contact
the TA who graded it within one week of having the grade returned to you
through Piazza. After this one-week window, we may deny your request for
re-evaluation. Also, please keep in mind that your grade may go up or
down as a result of re-grading.

### Missed final exam

Students who miss the final quiz must report to their faculty advising
office within 72 hours of the missed exam, and must supply supporting
documentation. Only your faculty advising office can grant deferred
standing in a course. You must also notify your instructor prior to (if
possible) or immediately after the exam. Your instructor will let you
know when you are expected to write your deferred exam. Deferred exams
will ONLY be provided to students who have applied for and received
deferred standing from their faculty.

### Academic concession policy

Please see [UBC's concession
policy](http://www.calendar.ubc.ca/vancouver/index.cfm?tree=3,329,0,0)
for detailed information on dealing with missed coursework, quizzes, and
exams under circumstances of an acute and unanticipated nature.

### Academic integrity

The academic enterprise is founded on honesty, civility, and integrity.
As members of this enterprise, all students are expected to know,
understand, and follow the codes of conduct regarding academic
integrity. At the most basic level, this means submitting only original
work done by you and acknowledging all sources of information or ideas
and attributing them to others as required. This also means you should
not cheat, copy, or mislead others about what is your work. Violations
of academic integrity (i.e., misconduct) lead to the breakdown of the
academic enterprise, and therefore serious consequences arise and harsh
sanctions are imposed. For example, incidences of plagiarism or cheating
may result in a mark of zero on the assignment or exam and more serious
consequences may apply if the matter is referred to the President’s
Advisory Committee on Student Discipline. Careful records are kept in
order to monitor and prevent recurrences.

A more detailed description of academic integrity, including the
University’s policies and procedures, may be found in the Academic
Calendar at
<http://calendar.ubc.ca/vancouver/index.cfm?tree=3,54,111,0>.

### Plagiarism

Students must correctly cite any code or text that has been authored by
someone else or by the student themselves for other assignments. Cases
of plagiarism may include, but are not limited to:

-   the reproduction (copying and pasting) of code or text with none or
    minimal reformatting (e.g., changing the name of the variables)
-   the translation of an algorithm or a script from a language to
    another
-   the generation of code by automatic code-generation software

An "adequate acknowledgement" requires a detailed identification of the
(parts of the) code or text reused and a full citation of the original
source code that has been reused.

The above attribution policy applies only to assignments. **No code or
text may be copied (with or without attribution) from any source during
a quiz or exam. Answers must always be in your own words. At a minimum,
copying will result in a grade of 0 for the related question.**

**Repeated plagiarism of any form could result in larger penalties,
including failure of the course.**

## Attribution

Parts of this syllabus (particularly the policies) have been copied and
derived from the [UBC MDS
Policies](https://ubc-mds.github.io/policies/).